/**
 * Kirpik comparison database: the Shopify App Store "Anti-theft" category.
 *
 * Ground rules (legal, binding):
 *  - Every factual statement about a competitor comes from its own public
 *    Shopify App Store listing as recorded in June and July 2026. Claims are
 *    quoted or closely paraphrased.
 *  - Limitations are stated as general, verifiable behaviour of browsers and
 *    platforms, never as a defect of a named app.
 *  - No opinion adjectives about competitors. Capability cells are derived
 *    from each app's stated mechanisms; anything a listing does not state is
 *    marked "unstated".
 */

export type MechanismId =
  | "right-click-block"
  | "copy-paste-block"
  | "keyboard-shortcut-block"
  | "devtools-block"
  | "screenshot-deter"
  | "overlay-trick"
  | "spy-extension-block"
  | "country-ip-block"
  | "visible-image-watermark"
  | "invisible-image-watermark"
  | "c2pa-metadata"
  | "copy-monitoring"
  | "takedown-service"
  | "invisible-text-watermark";

export interface Mechanism {
  label: string;
  what: string; // neutral description of what the technique does
  bypass: string[]; // general browser/platform facts; empty when not applicable
  note?: string; // shown when there is no bypass list, or as a closing line
}

export const MECHANISMS: Record<MechanismId, Mechanism> = {
  "right-click-block": {
    label: "Right-click and save-menu blocking",
    what: "A storefront script cancels the browser's context menu, so Copy and Save image as never appear, and often blocks image dragging too.",
    bypass: [
      "Shopify publishes every store's product data through public feed surfaces such as /products.json, and those are served without any storefront JavaScript running, so the script never loads there.",
      "Ctrl+A then Ctrl+C, or the browser's own Edit menu, copies the page text without touching the context menu.",
      "Reader mode, Save page as, and view-source all present the full text with page scripts stripped.",
      "Turning JavaScript off removes the block entirely; the page still renders.",
    ],
  },
  "copy-paste-block": {
    label: "Copy, paste, and text-selection blocking",
    what: "A script cancels selection and clipboard events, usually paired with a CSS user-select rule, so highlighting and copying stop working on the page.",
    bypass: [
      "The text is delivered inside the page HTML before any script runs. View-source (Ctrl+U) shows all of it, ready to copy.",
      "Reader mode strips a page's scripts and styles, including user-select rules, and presents clean, selectable text.",
      "Scrapers and catalogue importers read the raw HTML or the store's public product feed directly and never execute the blocking script.",
      "Turning JavaScript off restores normal selection and copying.",
    ],
  },
  "keyboard-shortcut-block": {
    label: "Keyboard-shortcut blocking",
    what: "A script intercepts key combinations such as Ctrl+C, Ctrl+U, Ctrl+S, and Ctrl+P while the page has focus.",
    bypass: [
      "A page script only sees keys pressed inside its own browser tab. It cannot reach the operating system or any other application.",
      "The same copy, save, and print actions exist in the browser's menus, where no shortcut is needed.",
      "None of it changes the HTML that a crawler, scraper, or feed reader downloads.",
    ],
  },
  "devtools-block": {
    label: "Developer-tools and view-source blocking",
    what: "A script tries to detect or discourage opening the browser developer tools or viewing the page source.",
    bypass: [
      "Developer tools open from the browser's own menu, or before the page loads, outside anything a page script can see.",
      "Prefixing an address with view-source:, or using Save page as, reads the same HTML without triggering a detector.",
      "The same content is available in the store's public feed surfaces, where no detector runs at all.",
    ],
  },
  "screenshot-deter": {
    label: "Screenshot blocking (claimed)",
    what: "Some listings say they prevent Print Screen or screen capture, usually by watching for the Print Screen key inside the page.",
    bypass: [
      "Browsers do not expose any API that lets a web page prevent screenshots. Operating-system capture tools, such as Win+Shift+S on Windows or Shift+Cmd+4 on macOS, work outside the page.",
      "For text, a screenshot is not even the easy route: free OCR tools turn a photographed paragraph back into editable text.",
      "A page script can, at most, react to the Print Screen key pressed inside its own tab. Capture tools do not use that key.",
    ],
  },
  "overlay-trick": {
    label: "Transparent overlay or blank-file swap",
    what: "An invisible layer sits over the content, or a casual image save is served a blank file, so a quick grab collects nothing useful.",
    bypass: [
      "The genuine file still has to be delivered to be displayed. It appears in the browser's network panel and page info, where it can be saved.",
      "Page text sits underneath as ordinary HTML. An overlay changes nothing about what view-source, a scraper, or a feed reader receives.",
      "A screenshot captures the rendered page, overlay or not.",
    ],
  },
  "spy-extension-block": {
    label: "Spy-extension blocking",
    what: "A script tries to detect known competitor-research browser extensions, such as product and sales trackers, and disrupt them.",
    bypass: [
      "Detection matches a list of known extensions. Renamed, updated, or new tools are not on the list.",
      "It has no effect on collection done outside a browser session, such as reading the public product feed from a server.",
      "An ordinary visitor selecting and copying text is not a spy extension, and is unaffected.",
    ],
  },
  "country-ip-block": {
    label: "Country, IP, and VPN blocking",
    what: "Restricts which regions, IP addresses, or connection types can load the store.",
    bypass: [
      "A VPN or proxy changes an apparent location in one click.",
      "Access control decides who can load the store. It says nothing about what happens to text after an allowed visitor, or a permitted crawler, has it.",
      "It is a who-can-enter rule, not a property of the content, so nothing about the words themselves changes.",
    ],
  },
  "visible-image-watermark": {
    label: "Visible image watermark",
    what: "Stamps a logo, text, or badge onto product photos server-side, so a copied image carries a visible mark.",
    bypass: [
      "A mark near an edge can be cropped away, and generative inpainting tools reconstruct the area under a mark across the whole image.",
      "The mark exists only on image files. The product description beside those images carries nothing, because there is no visible equivalent for text that a thief would keep.",
    ],
    note: "The mark genuinely travels with a copied image, which is a real advantage over any blocker. It is an image technique; text is outside its scope.",
  },
  "invisible-image-watermark": {
    label: "Invisible image watermark",
    what: "Embeds an identifying signal inside the pixels of an image rather than on top of it, so the photo looks unchanged.",
    bypass: [],
    note: "Resilience to editing, whether a copy can be identified elsewhere, and what a detection produces all depend on the engine and the app around it. And it applies to pixels: a product description has none, so this class of watermark cannot be applied to text.",
  },
  "c2pa-metadata": {
    label: "C2PA metadata and Content Credentials",
    what: "Attaches signed provenance metadata alongside a file, recording who made it and how it was edited.",
    bypass: [
      "Metadata travels beside content, not inside it. Text copied out of a page carries no metadata at all: a clipboard holds characters, nothing more.",
      "Many platforms and CDNs re-encode uploads and strip file metadata in the process.",
      "Credentials disclose provenance on content that still carries them. They do not follow a copy that leaves them behind.",
    ],
  },
  "copy-monitoring": {
    label: "Copy monitoring",
    what: "A server-side service scans chosen sites, or the wider web, for images or text matching yours and reports lookalikes.",
    bypass: [
      "A match shows that two pages carry similar content. On its own it does not show whose content it was first.",
      "Coverage follows where the service looks. A copy outside the scanned set is not found.",
      "Nothing is embedded in the content itself, so the copy carries no marker tying it back to its origin.",
    ],
  },
  "takedown-service": {
    label: "Takedown service",
    what: "A service finds infringing sites or marketplace listings and files removal requests on your behalf.",
    bypass: [
      "A takedown stands on evidence of ownership. The filing is only as strong as the proof behind it.",
      "It acts after a copy has appeared. It does not mark or trace the content beforehand.",
    ],
  },
  "invisible-text-watermark": {
    label: "Invisible text watermarking",
    what: "Embeds an invisible algorithmic watermark, derived from the original text's signature, into the text itself, so any copy of the words can be identified and attributed.",
    bypass: [],
    note: "The honest limit of any text watermark: a full rewrite defeats it, because rewritten words are no longer the original text. Judge an implementation on what its detection reads back and what proof a detection produces.",
  },
};

export type Approach = "blocker" | "bundle" | "watermark" | "monitor" | "takedown";

export const APPROACHES: Approach[] = ["blocker", "bundle", "watermark", "monitor", "takedown"];

export const APPROACH_LABEL: Record<Approach, string> = {
  blocker: "Storefront script blocker",
  bundle: "Blocker and access-control bundle",
  watermark: "Image watermark",
  monitor: "Copy monitor",
  takedown: "Takedown service",
};

export const APPROACH_BLURB: Record<Approach, string> = {
  blocker:
    "Apps that add a script to the storefront to cancel right-click, text selection, copying, keyboard shortcuts, or the developer tools while a visitor is on the page. A script acts only inside a browser tab that runs it. Shopify's public feed surfaces are served without any storefront JavaScript, and nothing in the text itself changes, so a copy that does leave carries no trace of its origin.",
  bundle:
    "Apps that pair the same in-browser content blocking with country, IP, VPN, bot, or spy-extension filtering. The access rules decide who can load the store. For the words on the page, the protection half is the storefront script, with the same reach and the same limits.",
  watermark:
    "Apps that stamp a visible logo or text onto product images, or otherwise process the image files. A mark on an image genuinely travels with a copy of that image. These apps work on photos; the product description beside the photo is not part of what gets marked.",
  monitor:
    "Server-side services that scan other sites for content matching yours and report lookalikes, sometimes with evidence bundles. Monitoring finds matches; on its own, a match does not establish whose content it was first.",
  takedown:
    "Services that detect infringing sites or marketplace listings and file removal requests for you. They act on copies after they appear, and a filing stands on whatever ownership evidence exists for the content in question.",
};

/* ------------------------------------------------------------------------ */
/* Capabilities (text-focused)                                              */
/* ------------------------------------------------------------------------ */

export type Cell = true | false | "na" | "unstated";

export type CapId =
  | "protectsText"
  | "invisibleOnStorefront"
  | "noStorefrontScripts"
  | "travelsWithText"
  | "worksOnFeeds"
  | "detectAnywhere"
  | "proofArtifact";

export const CAPABILITIES: { id: CapId; label: string }[] = [
  { id: "protectsText", label: "Does anything for text content (descriptions, articles, pages)" },
  { id: "invisibleOnStorefront", label: "Invisible to shoppers, with normal browsing behaviour untouched" },
  { id: "noStorefrontScripts", label: "Adds no scripts to the storefront" },
  { id: "travelsWithText", label: "Protection travels with the text when it is copied off-site" },
  { id: "worksOnFeeds", label: "Has any effect on Shopify's public feed surfaces" },
  { id: "detectAnywhere", label: "Can identify a copy found anywhere on the web" },
  { id: "proofArtifact", label: "Produces an ownership or evidence document" },
];

export const KIRPIK_CAPS: Record<CapId, Cell> = {
  protectsText: true,
  invisibleOnStorefront: true,
  noStorefrontScripts: true,
  travelsWithText: true,
  worksOnFeeds: true,
  detectAnywhere: true,
  proofArtifact: true,
};

export interface Competitor {
  /** Our page path segment for featured apps; also the App Store handle unless url overrides. */
  slug: string;
  name: string;
  url: string; // public Shopify App Store listing
  developer?: string;
  launched?: string; // ISO date from the listing
  rating?: string;
  reviews?: number;
  pricing?: string;
  primary: Approach;
  featured: boolean;
  summary: string; // neutral one-liner
  claims?: string[]; // near-verbatim from the listing (June and July 2026)
  mechanisms?: MechanismId[];
  proofNote?: string; // extra neutral note for the proof section
  textNote?: string; // extra paragraph for "the text question"
  sameDeveloper?: boolean; // Tilkie only: same developer as Kirpik, disclosed
  capsOverride?: Partial<Record<CapId, Cell>>;
}

const SHOPIFY = (handle: string) => `https://apps.shopify.com/${handle}`;

/** Mechanisms that require a script running on the storefront. */
export const SCRIPT_MECHS: MechanismId[] = [
  "right-click-block",
  "copy-paste-block",
  "keyboard-shortcut-block",
  "devtools-block",
  "screenshot-deter",
  "overlay-trick",
  "spy-extension-block",
];

export function appCaps(c: Competitor): Record<CapId, Cell> {
  const m = new Set(c.mechanisms ?? []);
  const hasScript = SCRIPT_MECHS.some((x) => m.has(x));
  const geoOnly = !hasScript && m.has("country-ip-block");
  const imgWm = m.has("visible-image-watermark") || m.has("invisible-image-watermark");
  const monitors = m.has("copy-monitoring");
  const files = m.has("takedown-service");
  const caps: Record<CapId, Cell> = {
    // A copy/selection blocker does act on text while a visitor is on the page,
    // and a monitor that scans for copied text engages with text. Image-only
    // tools do not.
    protectsText: m.has("copy-paste-block") || m.has("keyboard-shortcut-block") || monitors ? true : false,
    invisibleOnStorefront: hasScript || m.has("visible-image-watermark") ? false : true,
    noStorefrontScripts: hasScript ? false : geoOnly ? "unstated" : true,
    // A mark on an image travels with the image; the text row is "na" for
    // image tools because text is outside their scope. Blockers embed nothing.
    travelsWithText: imgWm ? "na" : false,
    // Feed surfaces run no storefront JavaScript, so script apps are false by
    // mechanism. Watermarked image files do serve through feeds.
    worksOnFeeds: hasScript ? false : imgWm ? true : monitors || files ? "na" : "unstated",
    detectAnywhere: monitors || files ? true : m.has("invisible-image-watermark") ? "unstated" : false,
    proofArtifact: false,
  };
  return { ...caps, ...(c.capsOverride ?? {}) };
}

/* ------------------------------------------------------------------------ */
/* Featured apps (each gets a page at /compare/<slug>/)                     */
/* ------------------------------------------------------------------------ */

const FEATURED: Competitor[] = [
  {
    slug: "disable-mouse-right-click",
    name: "RT: Disable Right Click",
    url: SHOPIFY("disable-mouse-right-click"),
    developer: "RoarTheme",
    launched: "2021-02-01",
    rating: "4.9",
    reviews: 281,
    pricing: "Free",
    primary: "blocker",
    featured: true,
    summary:
      "A free storefront script that disables right-click, copying, image saving, keyboard shortcuts, and states PrintScreen and screen capture prevention.",
    claims: [
      "Disable right-click to prevent cutting, copying, and saving images",
      "Disable copy and paste, text selection, and highlighting",
      "Disable keyboard shortcuts for save, copy, and view source",
      "PrintScreen and screen capture prevention",
    ],
    mechanisms: [
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "screenshot-deter",
    ],
  },
  {
    slug: "disable-copy-paste-country",
    name: "Store Protection & Spy Blocker",
    url: SHOPIFY("disable-copy-paste-country"),
    developer: "Helpy",
    launched: "2021-09-08",
    rating: "4.7",
    reviews: 88,
    pricing: "Free plan; paid from $2.99/mo",
    primary: "bundle",
    featured: true,
    summary:
      "Combines in-browser content blocking with country, IP, VPN, and bot filtering, plus a spy-extension blocker aimed at tools such as ShopHunter and PPSpy.",
    claims: [
      "Smart Spy Block technology against tools such as ShopHunter, PPSpy, and Koala Inspector",
      "Disable right-click, copy and paste, and keyboard shortcuts",
      "Block countries, IP addresses, VPNs, and bots",
      "Screenshot blocking",
    ],
    mechanisms: [
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "screenshot-deter",
      "spy-extension-block",
      "country-ip-block",
    ],
  },
  {
    slug: "store-shield",
    name: "Dakaas Fraud Filter, Antitheft",
    url: SHOPIFY("store-shield"),
    developer: "Dakaas",
    launched: "2021-01-25",
    rating: "4.8",
    reviews: 232,
    pricing: "Free plan; paid from $2.99/mo",
    primary: "bundle",
    featured: true,
    summary:
      "A fraud and anti-theft bundle pairing content blocking with city-level geo blocking, IP blocking, VPN and Tor detection, and order screening.",
    claims: [
      "Disable right-click, copy and paste, and developer tools",
      "City-level geo blocking, IP blocking, and VPN and Tor detection powered by AI",
      "Auto-cancel risky orders, with Cloudflare and IPQualityScore integrations",
      "Screenshot prevention",
    ],
    mechanisms: [
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "screenshot-deter",
      "country-ip-block",
    ],
  },
  {
    slug: "no-spy",
    name: "NoSpy - Anti Fraud Spy Blocker",
    url: SHOPIFY("no-spy"),
    developer: "The Shop Tinkerers",
    launched: "2022-09-16",
    rating: "4.8",
    reviews: 63,
    pricing: "Free plan; paid from $4.99/mo",
    primary: "bundle",
    featured: true,
    summary:
      "Blocks right-click, copying, and image saving, filters visitors by state, IP, VPN, and bot status while whitelisting Googlebot, and targets spy extensions.",
    claims: [
      "Disable right-click, copy, and image saving",
      "Block by country and state, IP, VPN, and bots, while whitelisting Googlebot",
      "Block spy extensions",
      "Protect store data",
    ],
    mechanisms: [
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "screenshot-deter",
      "spy-extension-block",
      "country-ip-block",
    ],
  },
  {
    slug: "shogard",
    name: "Shogard: Security IP Bot Block",
    url: SHOPIFY("shogard"),
    developer: "Trusted apps",
    launched: "2023-11-17",
    rating: "4.7",
    reviews: 41,
    pricing: "Free plan; paid from $7/mo",
    primary: "bundle",
    featured: true,
    summary:
      "Pairs storefront content blocking with IP, country, and bot controls, and states protection for product descriptions and blog posts.",
    claims: [
      "Prevent any sort of unauthorized image downloads",
      "Protect product descriptions and blog posts from copying",
      "Track and block IP addresses, countries, and bots",
      "Block checkout for selected countries, emails, or users",
    ],
    mechanisms: [
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "country-ip-block",
    ],
  },
  {
    slug: "kedra-shield-website-security",
    name: "Kedra Fraud Filter, IP Blocker",
    url: SHOPIFY("kedra-shield-website-security"),
    developer: "Kedra Apps",
    launched: "2024-07-01",
    rating: "4.4",
    reviews: 119,
    pricing: "Free plan; paid from $7.99/mo",
    primary: "bundle",
    featured: true,
    summary:
      "A security bundle with content blocking plus country, IP, VPN, bot, ASN, ISP, and referrer filtering, and a stated screenshot block.",
    claims: [
      "Disable right-click, copy, and developer tools",
      "Block countries, IPs, VPNs, and bots, plus ASN, ISP, and referrer blocking",
      "Screenshot blocking",
      "Spy extension blocking",
    ],
    mechanisms: [
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "screenshot-deter",
      "spy-extension-block",
      "country-ip-block",
    ],
  },
  {
    slug: "free-watermarks",
    name: "Easy Watermarks | Engage",
    url: SHOPIFY("free-watermarks"),
    developer: "Engage Apps",
    launched: "2017-11-17",
    rating: "4.7",
    reviews: 303,
    pricing: "Free plan; paid from $9.99/mo",
    primary: "watermark",
    featured: true,
    summary:
      "The category's most-reviewed watermark app: bulk visible logo, text, and sticker watermarks for product images, with optional right-click and copy blocking.",
    claims: [
      "One-click watermarking with logos, text, and a library of over 200 stickers",
      "Automatically watermark new products",
      "Disable right-click, copy and paste, and image download",
      "Original images are kept and restorable",
    ],
    mechanisms: ["visible-image-watermark", "right-click-block", "copy-paste-block"],
  },
  {
    slug: "cozy-antitheft-for-images-and-more",
    name: "Cozy AntiTheft",
    url: SHOPIFY("cozy-antitheft-for-images-and-more"),
    developer: "eCommerce Addons",
    launched: "2018-09-26",
    rating: "4.8",
    reviews: 230,
    pricing: "Free",
    primary: "blocker",
    featured: true,
    summary:
      "A long-running free blocker that disables right-click, shortcuts, drag-and-drop, printing, and the developer console, and describes itself as making theft harder.",
    claims: [
      "Disable right-click, keyboard shortcuts, and drag-and-drop",
      "Disable page printing, console, and developer tools",
      "Makes it harder to steal content",
    ],
    mechanisms: [
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
    ],
    proofNote:
      "Cozy AntiTheft's own listing frames the result as making it harder to steal content, which is an accurate description of what an in-browser blocker can do: add friction inside the tab, without changing what a copy carries once it leaves.",
  },
  {
    slug: "storelock",
    name: "StoreLock Copyright Protection",
    url: SHOPIFY("storelock"),
    developer: "Williams Web Services",
    launched: "2023-06-30",
    rating: "4.6",
    reviews: 8,
    pricing: "$4.99/mo plus $0.20 per image",
    primary: "takedown",
    featured: true,
    summary:
      "One of two takedown services in the category: automatic detection of counterfeit websites impersonating your store, with takedown requests sent from a dashboard, plus storefront blocking.",
    claims: [
      "Detect counterfeit websites impersonating your store automatically",
      "Send takedown requests from the dashboard",
      "Disable right-click and copying",
      "Country and IP blocking",
    ],
    mechanisms: [
      "takedown-service",
      "copy-monitoring",
      "right-click-block",
      "copy-paste-block",
      "country-ip-block",
    ],
    proofNote:
      "StoreLock's listing describes detecting impersonating sites and filing takedowns from a dashboard. A takedown request stands on evidence of ownership. For text, that is the difficult part: copied words carry nothing of their origin by default, which is the gap an embedded watermark is built to close.",
  },
  {
    slug: "viking-watermark",
    name: "Viking Watermark & Anti Theft",
    url: SHOPIFY("viking-watermark"),
    developer: "Aegis",
    launched: "2026-05-27",
    rating: "5.0",
    reviews: 3,
    pricing: "Free plan; paid from $5/mo",
    primary: "watermark",
    featured: true,
    summary:
      "Bulk visible watermarking of product images by collection or tag, applied automatically on upload, with originals kept and optional right-click blocking.",
    claims: [
      "Bulk watermark by collection or tag",
      "Automatically watermark images on upload",
      "Original images are kept",
      "Disable right-click and image copying",
    ],
    mechanisms: ["visible-image-watermark", "right-click-block", "copy-paste-block"],
  },
  {
    slug: "suprimg-anti-theft-watermark",
    name: "SuprImg: Anti-theft Watermark",
    url: SHOPIFY("suprimg-anti-theft-watermark"),
    developer: "Girls Who Web",
    launched: "2024-04-01",
    rating: "3.6",
    reviews: 17,
    pricing: "Free to install; paid $5/mo",
    primary: "watermark",
    featured: true,
    summary:
      "Adds visible text or logo watermarks to product images, compresses images, and can disable right-click, the developer console, and text copying.",
    claims: [
      "Add a custom text or logo watermark",
      "Compress images",
      "Disable right-click, the developer console, and text copy",
    ],
    mechanisms: [
      "visible-image-watermark",
      "right-click-block",
      "copy-paste-block",
      "devtools-block",
    ],
  },
  {
    slug: "oh-watermark",
    name: "Oh: Product Image Watermark",
    url: SHOPIFY("oh-watermark"),
    developer: "OptimizeHub",
    launched: "2026-01-13",
    pricing: "Free plan; paid from $4.99/mo",
    primary: "watermark",
    featured: true,
    summary:
      "Bulk and automatic visible watermarking for product images with a storefront overlay option, a 30-day restore window, and a stated aim of reducing casual copying.",
    claims: [
      "Bulk and automatic watermarking of product images",
      "Storefront overlay watermark",
      "Disable right-click and image dragging",
      "Reduce casual copying",
      "30-day restore of original images",
    ],
    mechanisms: ["visible-image-watermark", "overlay-trick", "right-click-block"],
    proofNote:
      "Oh's listing describes its goal as reducing casual copying, which matches what visible marks and storefront blocks can deliver. The description text beside the marked images is not part of what the app changes.",
  },
  {
    slug: "photolock",
    name: "Photolock",
    url: SHOPIFY("photolock"),
    developer: "Pasilobus",
    launched: "2016-05-18",
    rating: "3.9",
    reviews: 35,
    pricing: "Free plan; paid from $5/mo",
    primary: "blocker",
    featured: true,
    summary:
      "The oldest app in the category: browser-side blocking plus an image shield, a Screenshot Shield tier, and a paid-tier claim of invisible watermarks that identify who screenshots product images.",
    claims: [
      "Block right-clicks, screenshots, and copying",
      "Invisible watermarks identify who screenshots your product images",
      "Image shields replace saved images with blank transparent files",
      "Detect and block spy extensions",
    ],
    mechanisms: [
      "invisible-image-watermark",
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "screenshot-deter",
      "overlay-trick",
      "spy-extension-block",
    ],
    proofNote:
      "Photolock is one of two apps in this category whose listing claims an invisible watermark. The claim is framed around identifying who screenshots product images on your own store. The listing does not describe checking a page elsewhere on the web for the mark, or producing an ownership document from a detection. It is also an image-side mark: the product description text next to those images carries nothing.",
  },
  {
    slug: "imagearmor",
    name: "Image Armor - Bulk Watermark",
    url: SHOPIFY("imagearmor"),
    developer: "Image Armor",
    launched: "2025-09-01",
    rating: "4.3",
    reviews: 3,
    pricing: "Paid; from $9/mo",
    primary: "watermark",
    featured: true,
    summary:
      "A watermark-only app: customizable visible text or image watermarks applied to product images in bulk, with originals backed up. No storefront blocking.",
    claims: [
      "Customizable text or image watermarks",
      "Bulk watermarking of product images",
      "Original images are backed up",
    ],
    mechanisms: ["visible-image-watermark"],
  },
  {
    slug: "ip-moat",
    name: "IP Moat - Counterfeit Defence",
    url: SHOPIFY("ip-moat"),
    developer: "IP Moat Ltd",
    launched: "2024-10-14",
    rating: "5.0",
    reviews: 3,
    pricing: "Free audit; plans $105 to $529/mo",
    primary: "takedown",
    featured: true,
    summary:
      "A managed counterfeit-enforcement service: AI scanning of online marketplaces with one-click removals, priced as a professional service rather than a storefront app.",
    claims: [
      "Let our AI scan online marketplaces",
      "One-click removals",
      "DMCA and marketplace takedowns",
    ],
    mechanisms: ["copy-monitoring", "takedown-service"],
    proofNote:
      "IP Moat's listing describes a monitoring and enforcement service operated for you, priced accordingly. That is a different job from marking content: the service finds and files, and any filing still rests on the ownership evidence available for the content in question. For product copy, an embedded watermark is one way to have that evidence ready before it is needed.",
  },
  {
    slug: "spyblocker-block-competitors",
    name: "SpyBlocker - Block Competitors",
    url: SHOPIFY("spyblocker-block-competitors"),
    developer: "Snow John",
    launched: "2025-05-27",
    rating: "5.0",
    reviews: 1,
    pricing: "Free",
    primary: "blocker",
    featured: true,
    summary:
      "A free blocker that discloses it runs as a lightweight JS SDK, combining right-click, copy, and screenshot blocking with IP and bot filtering and an invisible watermark intended to discourage screenshots.",
    claims: [
      "Disable right-click, copy, and screenshots",
      "Invisible watermark to discourage screenshots",
      "Block countries, IPs, and bots with user-agent filtering",
      "Lightweight JS SDK",
    ],
    mechanisms: [
      "invisible-image-watermark",
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
      "screenshot-deter",
      "country-ip-block",
    ],
    proofNote:
      "SpyBlocker is the second app in the category to mention an invisible watermark, described as a way to discourage screenshots, with no stated mechanism, detection flow, or proof output. Its listing also discloses that the app is a lightweight JS SDK, which is a clearer statement than most listings make: everything it does happens in the visitor's browser.",
  },
  {
    slug: "disable-right-click",
    name: "MenuLock - Disable Right Click",
    url: SHOPIFY("disable-right-click"),
    developer: "Impress",
    launched: "2017-11-03",
    rating: "3.7",
    reviews: 29,
    pricing: "Free plan; Pro $2/mo",
    primary: "blocker",
    featured: true,
    summary:
      "Disables right-click Save As, text selection, cut and copy, and drag-and-drop on desktop, with mobile coverage on the paid plan.",
    claims: [
      "Disable Save Image As, text selection, cut and copy, and drag-and-drop",
      "No banners or popups for customers",
      "Works on mobile on the Pro plan",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
  },
  {
    slug: "sgtlab-bulk-watermark",
    name: "Bulk Watermark SGTLab",
    url: SHOPIFY("sgtlab-bulk-watermark"),
    developer: "SGTLab",
    launched: "2024-03-15",
    rating: "3.1",
    reviews: 6,
    pricing: "Free credits; packs $4.50 to $65",
    primary: "watermark",
    featured: true,
    summary:
      "A pure watermarking tool: visible logo or text watermarks applied to product images in bulk on pay-as-you-go credits, with revert to originals.",
    claims: [
      "Bulk watermark product images",
      "Pay-as-you-go credits",
      "Revert to original photos",
    ],
    mechanisms: ["visible-image-watermark"],
  },
  {
    slug: "addify-image-watermark",
    name: "Addify Image Watermark",
    url: SHOPIFY("addify-image-watermark"),
    developer: "Addify",
    launched: "2024-10-02",
    rating: "3.7",
    reviews: 3,
    pricing: "Paid; $4.99 to $7.99/mo",
    primary: "watermark",
    featured: true,
    summary:
      "Visible text or image watermarks with bulk rules and automatic application to new images, keeping the originals for restore.",
    claims: [
      "Text or image watermarks with bulk rules",
      "Auto-apply watermarks to new images",
      "Original images are kept",
    ],
    mechanisms: ["visible-image-watermark"],
  },
  {
    slug: "defendify",
    name: "Defendify: Copyright AntiTheft",
    url: SHOPIFY("defendify"),
    developer: "DJP Digital",
    launched: "2022-05-06",
    rating: "5.0",
    reviews: 4,
    pricing: "Free plan",
    primary: "blocker",
    featured: true,
    summary:
      "A free blocker whose listing describes itself, accurately, as an extra layer of deterrence against casual content theft.",
    claims: [
      "An extra layer of deterrence against casual content theft",
      "Disable right-click and Save As context menus",
      "Disable certain keyboard shortcuts",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
    proofNote:
      "Defendify's own wording, an extra layer of deterrence against casual content theft, is the candid version of what every storefront blocker offers. Deterrence inside the tab is real; it is simply a different job from following the words after they leave.",
  },
  {
    slug: "tilkie-image-protection",
    name: "Tilkie - Image Protection",
    url: SHOPIFY("tikie-image-protection"),
    developer: "INFOWISE LIMITED",
    launched: "2026-05-05",
    pricing: "Free plan; paid $9.99/mo, Pro $29.99/mo",
    primary: "watermark",
    featured: true,
    sameDeveloper: true,
    summary:
      "Invisible neural watermarking for product images, with a detection engine and a Chain of Proof certificate. Built by the same team as Kirpik: Tilkie covers images, Kirpik covers text.",
    claims: [
      "Invisible neural watermarking for product images",
      "Detect copies of your images",
      "Chain of Proof certificate for takedowns",
    ],
    mechanisms: ["invisible-image-watermark"],
    capsOverride: {
      protectsText: false,
      detectAnywhere: true,
      proofArtifact: true,
      worksOnFeeds: true,
    },
    textNote:
      "Tilkie does nothing for text, in exactly the way Kirpik does nothing for images. The two apps split the same problem down the middle: photos carry Tilkie's invisible mark, copy carries Kirpik's. Many stores run both, and there is no bundling requirement in either direction.",
  },
  {
    slug: "mintallkeep",
    name: "Mintall Keep",
    url: SHOPIFY("mintallkeep"),
    developer: "Mintall",
    launched: "2025-10-07",
    pricing: "Free plan; paid $29 to $99/mo",
    primary: "monitor",
    featured: true,
    summary:
      "Provenance rather than watermarking: C2PA Content Credentials and NFT records attached to content, with IP monitoring and a stated no-badges, no-watermarks approach.",
    claims: [
      "C2PA Content Credentials and NFT provenance",
      "Legal-grade evidence",
      "IP monitoring",
      "No badges or watermarks",
      "Make your store trusted by AI buyers",
    ],
    mechanisms: ["c2pa-metadata", "copy-monitoring"],
    capsOverride: {
      protectsText: "unstated",
      detectAnywhere: "unstated",
      proofArtifact: true,
      travelsWithText: false,
    },
    proofNote:
      "Mintall Keep's listing is explicit that it adds no watermark: it attaches C2PA Content Credentials and NFT records alongside content. Metadata of this kind travels beside a file rather than inside it, and text copied out of a page carries no metadata at all, so the credential stays behind while the words move. Credentials are a provenance disclosure for content that keeps them; they are a different instrument from a mark embedded in the content itself.",
  },
  {
    slug: "disable-right-click-3",
    name: "Disablo - Disable Right Click",
    url: SHOPIFY("disable-right-click-3"),
    developer: "Crucial Commerce Apps",
    launched: "2020-04-03",
    rating: "4.7",
    reviews: 25,
    pricing: "Free plan; Premium $0.99/mo",
    primary: "blocker",
    featured: true,
    summary:
      "Disables right-click Save image as, drag-and-drop, and copy, paste, and print shortcuts, with page-specific protection on the cheapest paid plan in the category.",
    claims: [
      "Disable Save image as and drag-and-drop, including background images",
      "Prevent copy, paste, and print keyboard shortcuts",
      "Mobile text and image protection",
      "Page-specific protection on Premium",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
  },
  {
    slug: "copycat-alert-product-monitor",
    name: "Spy Blocker (Copycat Monitor)",
    url: SHOPIFY("copycat-alert-product-monitor"),
    developer: "FlowIntegrity Drive",
    launched: "2026-06-01",
    pricing: "Free plan; paid $29.90 to $109.90/mo",
    primary: "monitor",
    featured: true,
    summary:
      "Despite the name, a monitor rather than a blocker: it scans domains you choose for copied images, copied text, and similar product pages, and assembles evidence packs.",
    claims: [
      "Scan chosen domains for copied images, copied text, and similar product pages",
      "Evidence packs",
    ],
    mechanisms: ["copy-monitoring"],
    capsOverride: { proofArtifact: true },
    proofNote:
      "This is one of the few listings in the category that engages with text at all: it scans selected domains for copied text and builds evidence packs from what it finds. A match found by scanning shows that two pages carry similar words. Pairing monitoring with a mark embedded in the text itself is what turns a similarity into an attribution, which is why the two approaches complement rather than compete.",
  },
  {
    slug: "auto-image-watermark-seo",
    name: "Auto - Image Watermark & SEO",
    url: SHOPIFY("auto-image-watermark-seo"),
    developer: "Alpha Edge",
    launched: "2026-06-15",
    pricing: "Free plan; paid $2.99 to $39.99/mo",
    primary: "watermark",
    featured: true,
    summary:
      "Bulk visible watermarking across products, collections, blogs, and files, with automatic watermarking of new images, restore, an optional blocking bundle, and image SEO extras.",
    claims: [
      "Bulk watermark products, collections, blogs, and files",
      "Auto-watermark new images, with restore",
      "SEO extras: ALT text, file renaming, WebP conversion",
      "Optional storefront blocking bundle",
    ],
    mechanisms: ["visible-image-watermark", "right-click-block", "copy-paste-block"],
  },
  {
    slug: "copyblock",
    name: "CopyBlock",
    url: SHOPIFY("copyblock"),
    developer: "Syntax Design",
    launched: "2026-05-28",
    pricing: "$5/mo",
    primary: "blocker",
    featured: true,
    summary:
      "A theme-editor embed that disables right-click, copy, drag, and shortcuts while keeping search, signup, and checkout working, with the category's plainest self-description: discourage casual copying.",
    claims: [
      "Discourage casual copying on your storefront",
      "Disable right-click, copy, drag, and shortcuts",
      "Keeps search, signup, and checkout working",
      "Installs as a theme-editor embed",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
    proofNote:
      "CopyBlock's listing says exactly what a storefront blocker does: discourage casual copying. That framing needs no correction. The open question for a store owner is what happens to the copies that casual friction does not stop, and that is a question about evidence, not blocking.",
  },
  {
    slug: "qf-content-guard",
    name: "QF Content Guard",
    url: SHOPIFY("qf-content-guard"),
    developer: "QF Network",
    launched: "2026-02-18",
    pricing: "$25/mo",
    primary: "watermark",
    featured: true,
    summary:
      "Bulk image watermarking with restore, combined with an Advanced Anti-Theft Storefront Shield covering right-click, copy, drag, developer tools, and shortcuts.",
    claims: [
      "Bulk image watermarking with restore",
      "Advanced Anti-Theft Storefront Shield",
      "Disable right-click, copy, drag, developer tools, and shortcuts",
    ],
    mechanisms: [
      "visible-image-watermark",
      "right-click-block",
      "copy-paste-block",
      "keyboard-shortcut-block",
      "devtools-block",
    ],
  },
];

/* ------------------------------------------------------------------------ */
/* Remaining apps. Every app here also gets a page at /compare/<slug>/.     */
/* Seven apps listed in the App Store category but outside content          */
/* protection entirely (theme backups, consent compliance, coupon control,  */
/* PII scanning, patent drawings, member gating) are excluded from the site */
/* and do not appear in this file.                                          */
/* ------------------------------------------------------------------------ */

const TABLE_ONLY: Competitor[] = [
  {
    slug: "easy-block-customer-ip-country",
    name: "Securify Fraud Country Blocker",
    url: SHOPIFY("easy-block-customer-ip-country"),
    developer: "siimple.ai",
    launched: "2023-04-21",
    rating: "4.5",
    reviews: 78,
    pricing: "Free plan; paid $5.99 to $49/mo",
    primary: "bundle",
    featured: false,
    summary: "Right-click, copy, and image-save blocking combined with country, IP, VPN, bot, and spy-extension filtering.",
    claims: [
      "Disable right-click, image saving and copy-paste to stop content scrapers fast",
      "Block countries, IP addresses, VPNs, and bots",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "sales-shield",
    name: "Sales Shield: Store Protection",
    url: SHOPIFY("sales-shield"),
    developer: "AAZ",
    launched: "2021-07-08",
    rating: "4.7",
    reviews: 16,
    pricing: "Free plan; paid from $4.74/mo",
    primary: "bundle",
    featured: false,
    summary: "Content blocking plus spy-extension, country, and IP filtering, with a feature that generates fake data for trackers.",
    claims: [
      "Disable right-click, keyboard shortcuts, save image, and select text",
      "Block spy extensions, countries, and IPs",
      "Generate fake data for trackers",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "x-shield-store-guard",
    name: "X Shield: Fraud & Bot Blocker",
    url: SHOPIFY("x-shield-store-guard"),
    developer: "B2B Gold",
    launched: "2025-07-14",
    rating: "4.7",
    reviews: 10,
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Country, IP, VPN, and bot filtering with content blocking, whitelisting search and AI crawlers by design.",
    claims: [
      "Country blocking with region presets",
      "Bot blocking that welcomes Googlebot, Bingbot, and AI crawlers",
      "Developer-tools detection and spy-extension blocking",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "antitheft-pro",
    name: "Disable Right Click AntiTheft",
    url: SHOPIFY("antitheft-pro"),
    developer: "CMG INFOTECH",
    launched: "2025-07-01",
    rating: "4.8",
    reviews: 16,
    pricing: "Free",
    primary: "blocker",
    featured: false,
    summary: "Free blocker covering right-click, inspect element, copy, shortcuts, and printing, with broad protection wording.",
    claims: [
      "Block right-click and inspect element",
      "Disable copy, paste, and keyboard shortcuts",
      "Protect website code, sales data, and customer data",
      "Block web scraping",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter"],
  },
  {
    slug: "protos",
    name: "Protos: Anti Fraud Spy Blocker",
    url: SHOPIFY("protos"),
    developer: "Algo Commerce",
    launched: "2025-03-03",
    rating: "4.5",
    reviews: 7,
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Free content blocking with country, IP, VPN, Tor, and bot filtering.",
    claims: ["Disable right-click and copying", "Block countries, IPs, VPN and Tor, and bots"],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "country-ip-block"],
  },
  {
    slug: "scala-anti-spy",
    name: "Scala Anti Spy",
    url: SHOPIFY("scala-anti-spy"),
    developer: "SCALA",
    launched: "2022-08-24",
    rating: "5.0",
    reviews: 5,
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Free blocker with country filtering and adjustable protection levels.",
    claims: [
      "Disable right-click, copy, and image saving",
      "Block certain countries and regions",
      "Screenshot blocking",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "shop-shield",
    name: "Shop Shield Pro",
    url: SHOPIFY("shop-shield"),
    developer: "Uplinkly",
    launched: "2019-06-14",
    rating: "5.0",
    reviews: 1,
    pricing: "Free",
    primary: "blocker",
    featured: false,
    summary: "Free blocker with right-click, image, and copy blocking and a mode it names Nuclear Mode.",
    claims: ["Block right-click, image saving, and copying", "Block reverse engineering tools", "Nuclear Mode"],
    mechanisms: ["right-click-block", "copy-paste-block"],
  },
  {
    slug: "country-blockeer",
    name: "Geoshield - Country blocker",
    url: SHOPIFY("country-blockeer"),
    developer: "XYZ Apps",
    launched: "2025-03-28",
    rating: "4.7",
    reviews: 14,
    pricing: "$2.29 to $4.29/mo",
    primary: "bundle",
    featured: false,
    summary: "Country allowlists and redirects with right-click and copy blocking and bot filtering.",
    claims: ["Country allowlists and redirects", "Disable right-click and copying", "Bot blocking"],
    mechanisms: ["right-click-block", "copy-paste-block", "country-ip-block"],
  },
  {
    slug: "shop-protector-1",
    name: "Shop Protector",
    url: SHOPIFY("shop-protector-1"),
    developer: "DPSolution",
    launched: "2025-05-12",
    rating: "4.0",
    reviews: 14,
    pricing: "$1.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Blocks developer tools, right-click, and copying with country restrictions, and describes itself as a client-side tool.",
    claims: [
      "Block access to developer tools (F12)",
      "Disable right-click, copy, and text selection",
      "Restrict the site from selected countries",
      "A client-side tool",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "country-ip-block"],
  },
  {
    slug: "shieldify",
    name: "Shieldify - Store Protection",
    url: SHOPIFY("shieldify"),
    developer: "Webomnific",
    launched: "2023-06-06",
    rating: "5.0",
    reviews: 4,
    pricing: "$3.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Country, VPN, and spy filtering with right-click, copy, and print blocking and a console legal warning.",
    claims: ["Country, VPN, and spy blocking", "Disable right-click, copying, and printing", "Console legal warning"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "koi-disable-right-click",
    name: "KOI NoSpy: Disable Right Click",
    url: SHOPIFY("koi-disable-right-click"),
    developer: "Yield Tech Hub",
    launched: "2024-09-05",
    rating: "4.1",
    reviews: 3,
    pricing: "Free plan; paid from $2.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Content blocking plus IP and country filtering, targeting named spy extensions.",
    claims: [
      "Disable right-click, copy, and screenshots",
      "Block spy extensions such as PPSpy and UUSpy",
      "IP and country blocking",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "securecommerce-1",
    name: "SecurEcommerce Shop Protection",
    url: SHOPIFY("securecommerce-1"),
    developer: "PearlProtect",
    launched: "2025-10-10",
    rating: "4.6",
    reviews: 3,
    pricing: "Free plan; paid $10 to $19/mo",
    primary: "bundle",
    featured: false,
    summary: "Content blocking and access filtering with clone detection and redirect, AI email analysis, and SSL monitoring.",
    claims: [
      "Disable right-click and copying",
      "Block countries, IPs, VPNs, and bots",
      "Clone detection and redirect",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "country-ip-block"],
  },
  {
    slug: "bl-content-protection",
    name: "BL Content Protection",
    url: SHOPIFY("bl-content-protection"),
    developer: "BACKLIP",
    launched: "2024-11-05",
    rating: "5.0",
    reviews: 2,
    pricing: "$1.99/mo",
    primary: "blocker",
    featured: false,
    summary: "Right-click, copy, image-save, and shortcut blocking.",
    claims: ["Disable right-click, copying, image saving, and shortcuts"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block"],
  },
  {
    slug: "disable-right",
    name: "G: Anti Spy: Disable Right Click",
    url: SHOPIFY("disable-right"),
    developer: "GoodApps",
    launched: "2024-09-20",
    rating: "5.0",
    reviews: 4,
    pricing: "Free plan; paid $2.99 to $4.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Content blocking with geo and IP filtering, spy-extension alerts, and pricing tied to store order volume.",
    claims: [
      "Disable right-click, copy, and screenshots",
      "Block spy extensions, with email alerts",
      "Geo and IP blocking",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "firewall-ip-and-country-restriction",
    name: "MO: Country Blocker & IP Block",
    url: SHOPIFY("firewall-ip-and-country-restriction"),
    developer: "miniOrange",
    launched: "2021-04-30",
    rating: "3.0",
    reviews: 13,
    pricing: "$9.99 to $19.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Country, state, and city blocking with IP, VPN, and bot filtering plus right-click and copy blocking.",
    claims: ["Block by country, state, and city", "IP, VPN, and bot blocking", "Disable right-click and copying"],
    mechanisms: ["right-click-block", "copy-paste-block", "country-ip-block"],
  },
  {
    slug: "easy-block",
    name: "Easy Block Guard",
    url: SHOPIFY("easy-block"),
    developer: "Limontech",
    launched: "2025-10-21",
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Access control only: blocking by country, IP, language, and timezone, pitched at content copying.",
    claims: ["Block by country, IP, language, and timezone"],
    mechanisms: ["country-ip-block"],
  },
  {
    slug: "mega-content-protector",
    name: "Mega Content Protector",
    url: SHOPIFY("mega-content-protector"),
    developer: "Mega Profit Apps",
    launched: "2023-08-01",
    rating: "5.0",
    reviews: 4,
    pricing: "$2.49 to $2.99/mo",
    primary: "blocker",
    featured: false,
    summary: "Copy, drag, shortcut, right-click, console, and print blocking on desktop and mobile, including background images.",
    claims: [
      "Disable copying, drag-and-drop, shortcuts, and right-click, including background images",
      "Disable console debugging and printing",
      "Prevent stealing your code or finding security vulnerabilities",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block"],
  },
  {
    slug: "shop-guard-app",
    name: "Shop Guard",
    url: SHOPIFY("shop-guard-app"),
    developer: "BeME Apps",
    launched: "2025-07-08",
    pricing: "Free plan; paid $9/mo",
    primary: "bundle",
    featured: false,
    summary: "Right-click, copy, shortcut, and touch-hold blocking with country filtering; the paid plan adds IP blocking and a GDPR banner.",
    claims: [
      "Disable right-click, copy, shortcuts, and touch-hold",
      "Country blocking; Pro adds IP blocking, GDPR banner, and white label",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "country-ip-block"],
  },
  {
    slug: "prevent-content-theft",
    name: "AntiCopy: Prevent Content Theft",
    url: SHOPIFY("prevent-content-theft"),
    developer: "Hura Apps",
    launched: "2018-09-26",
    rating: "3.8",
    reviews: 6,
    pricing: "$1/mo",
    primary: "bundle",
    featured: false,
    summary: "Right-click, shortcut, selection, and debugger blocking with country restrictions and admin-bar hiding.",
    claims: [
      "Disable right-click, keyboard shortcuts, text selection, and debugger",
      "Block visitors from certain countries",
      "Hide the Shopify badge",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "country-ip-block"],
  },
  {
    slug: "content-protection",
    name: "Content Protection by Webyze",
    url: SHOPIFY("content-protection"),
    developer: "Webyze",
    launched: "2016-11-14",
    rating: "4.0",
    reviews: 1,
    pricing: "$5/mo",
    primary: "bundle",
    featured: false,
    summary: "One of the category's oldest blockers, combining content blocking with spy and geo filtering.",
    claims: ["Disable right-click, copying, and screenshots", "Block web scraping and spy extensions"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "anty-spy",
    name: "Anti Spy - Filter, Blocker",
    url: SHOPIFY("anty-spy"),
    developer: "ImpactPixel",
    launched: "2023-01-16",
    rating: "5.0",
    reviews: 1,
    pricing: "Free to install; paid $9.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Spy-extension blocking with right-click, copy, and developer-tools blocking and a console warning.",
    claims: ["Blocking all forms of spy extensions", "Disable right-click, copy, and developer tools"],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "spy-extension-block"],
  },
  {
    slug: "nocopy-plagiarism-guard",
    name: "NoCopy Plagiarism Guard",
    url: SHOPIFY("nocopy-plagiarism-guard"),
    developer: "Marker",
    launched: "2026-03-25",
    pricing: "Free",
    primary: "blocker",
    featured: false,
    summary: "Free blocker with a copyright message and blocked-attempt analytics, and the category's clearest disclosure: it works as a theme embed.",
    claims: [
      "Disable right-click, copying, and shortcuts, with a copyright message",
      "Blocked-attempt analytics",
      "Works as a theme embed",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
  },
  {
    slug: "salesdish-content-protection",
    name: "Salesdish Content Protection",
    url: SHOPIFY("salesdish-content-protection"),
    developer: "DropshipNyc",
    launched: "2022-08-17",
    rating: "5.0",
    reviews: 1,
    pricing: "Free",
    primary: "blocker",
    featured: false,
    summary: "Free blocking of right-click, shortcuts, drag, selection, and printing, on desktop and mobile.",
    claims: ["Disable right-click, shortcuts, drag and selection, and printing", "Works on mobile"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
  },
  {
    slug: "shop-protector",
    name: "SB Disable Right Click",
    url: SHOPIFY("shop-protector"),
    developer: "SetuBridge",
    launched: "2022-01-07",
    pricing: "Free",
    primary: "blocker",
    featured: false,
    summary: "Free right-click, copy, and image-save blocking including view-source shortcuts.",
    claims: ["Disable right-click, copying, image saving, and view-source shortcuts (Ctrl+U, F12)"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block"],
  },
  {
    slug: "right-click-disable",
    name: "Disable Right Click Master",
    url: SHOPIFY("right-click-disable"),
    developer: "cloud1galaxy",
    launched: "2019-11-26",
    rating: "5.0",
    reviews: 1,
    pricing: "$1.99/mo",
    primary: "blocker",
    featured: false,
    summary: "Right-click, copy, and shortcut blocking with a stated aim of preventing visitors copying any content.",
    claims: ["Prevent your store visitors from copying any of your content", "Disable right-click, copying, and screenshots"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter"],
  },
  {
    slug: "switchboard-development",
    name: "Store Conversion Tools",
    url: SHOPIFY("switchboard-development"),
    developer: "Amethyst Applications",
    launched: "2026-05-07",
    pricing: "$1/mo per toggle",
    primary: "blocker",
    featured: false,
    summary: "A toggle suite whose Anti-Copy Content Shield is built, as the listing discloses, with native Theme App Extensions.",
    claims: ["Anti-Copy Content Shield toggle", "Built with native Theme App Extensions"],
    mechanisms: ["right-click-block", "copy-paste-block"],
  },
  {
    slug: "watchdog",
    name: "SAFE - Store Protection",
    url: SHOPIFY("watchdog"),
    developer: "Zynclabs",
    launched: "2025-02-27",
    rating: "3.1",
    reviews: 3,
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Free content blocking with country, IP, and bot filtering, age verification, and real-time alerts.",
    claims: [
      "Disable right-click, copy, and screenshots",
      "Country, IP, and bot blocking with real-time alerts",
      "Stop fraud before it happens",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "photosentry",
    name: "PhotoSentry: Image Protection",
    url: SHOPIFY("photosentry"),
    developer: "Zoidworks LLC",
    launched: "2026-03-30",
    pricing: "Free plan; paid $4.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Right-click and image-save blocking with geo and IP filtering and blocked-attempt tracking by location.",
    claims: ["Disable right-click and image saving", "Track blocked attempts by location", "Geo and IP blocking"],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "country-ip-block"],
  },
  {
    slug: "clipboard-manager",
    name: "Mega Anti-Theft",
    url: SHOPIFY("clipboard-manager"),
    developer: "Architechpro OÜ",
    launched: "2018-12-07",
    pricing: "$2.99/mo",
    primary: "blocker",
    featured: false,
    summary: "A blocker that also appends an attribution link to text copied to the clipboard.",
    claims: ["Disable right-click, image saving, and shortcuts", "Append an attribution link to copied text"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
  },
  {
    slug: "right-click-defender",
    name: "Ongoing Disable Right Click",
    url: SHOPIFY("right-click-defender"),
    developer: "Ongoing Apps",
    launched: "2018-05-01",
    rating: "5.0",
    reviews: 4,
    pricing: "$9.99/mo",
    primary: "blocker",
    featured: false,
    summary: "Right-click, copy, and developer-tools blocking with stated protection for blog posts and around-the-clock image protection.",
    claims: ["Blocks View Source", "Protects your blog posts from plagiarists", "Protects Images 24/7"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block"],
  },
  {
    slug: "speed-defender",
    name: "Speed Defender",
    url: SHOPIFY("speed-defender"),
    developer: "Speed Ecom",
    launched: "2021-01-18",
    rating: "5.0",
    reviews: 1,
    pricing: "$2.97/mo",
    primary: "blocker",
    featured: false,
    summary: "Copy blocking with stated source-code hiding, a Windows print-screen limit, and best-seller sort blocking.",
    claims: [
      "Hide storefront source code",
      "Limit print-screen capture on Windows devices",
      "Block best-seller sorting",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "screenshot-deter"],
  },
  {
    slug: "smart-security",
    name: "Smart Security",
    url: SHOPIFY("smart-security"),
    developer: "ENS Enterprises",
    launched: "2020-12-31",
    pricing: "Free plan; paid $1/mo",
    primary: "blocker",
    featured: false,
    summary: "Right-click and shortcut blocking with image protection.",
    claims: ["Disable right-click and shortcuts", "Disabling the right click solves the problem of online theft"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
  },
  {
    slug: "shopprotect",
    name: "ShopProtect",
    url: SHOPIFY("shopprotect"),
    developer: "COMCODE",
    launched: "2019-02-12",
    rating: "4.0",
    reviews: 4,
    pricing: "$4.99/mo",
    primary: "blocker",
    featured: false,
    summary: "Right-click, copy, drag, and shortcut blocking with theme-name and best-seller hiding.",
    claims: ["Disable right-click, copying, drag, and shortcuts", "Hide the theme name and best-seller sorting"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block"],
  },
  {
    slug: "dev-content-protector",
    name: "B&S - Spy Protect & IP blocker",
    url: SHOPIFY("dev-content-protector"),
    developer: "Boost And Sales",
    launched: "2024-12-19",
    pricing: "Free plan; paid $6.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Right-click, copy, and print blocking; the paid plan adds geo, IP, and spy-extension filtering against named tools.",
    claims: [
      "Disable right-click, copy, and printing",
      "Pro: geo, IP, and spy-extension blocking (PPSpy, AliHunter, and others)",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "store-fence",
    name: "Store Fence: Country Blocker",
    url: SHOPIFY("store-fence"),
    developer: "Zobtech",
    launched: "2025-07-17",
    rating: "1.0",
    reviews: 1,
    pricing: "Free plan; paid $4.99/mo",
    primary: "bundle",
    featured: false,
    summary: "State, city, and IP blocking combined with content blocking and bot filtering.",
    claims: ["Block states, cities, and IPs", "Disable right-click, copy, and screenshots", "Bot blocking"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "prevent-content-copying",
    name: "Protection Shield",
    url: SHOPIFY("prevent-content-copying"),
    developer: "CldmApps",
    launched: "2020-05-27",
    rating: "1.0",
    reviews: 1,
    pricing: "$2/mo",
    primary: "blocker",
    featured: false,
    summary: "Right-click, copy, developer-tools, and screenshot blocking.",
    claims: ["Disable right-click, copy, and screenshots"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter"],
  },
  {
    slug: "aegis",
    name: "Aegis - Anti Copy & Blacklist",
    url: SHOPIFY("aegis"),
    developer: "Fuznet",
    launched: "2018-10-04",
    rating: "1.4",
    reviews: 2,
    pricing: "$2.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Content blocking with best-seller protection and country filtering.",
    claims: ["Disable right-click and copying", "Best-seller protection", "Country blocking"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "dropship-protect",
    name: "Dropship Protect - Spy Protect",
    url: SHOPIFY("dropship-protect"),
    developer: "VD GROUP LLC",
    launched: "2024-07-03",
    rating: "1.0",
    reviews: 1,
    pricing: "Free plan; paid $7.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Spy-extension blocking against named research tools, with geo and IP filtering.",
    claims: ["Block spy tools such as AliHunter, PPSPY, and ShopHunter", "Geo and IP blocking"],
    mechanisms: ["spy-extension-block", "country-ip-block"],
  },
  {
    slug: "threads",
    name: "Threads",
    url: SHOPIFY("threads"),
    developer: "Threads SH",
    launched: "2024-02-20",
    rating: "1.0",
    reviews: 1,
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Country, proxy, and bot blocking with an image content-protection feature.",
    claims: ["Country and proxy/bot blocking", "Content protection for images"],
    mechanisms: ["country-ip-block"],
  },
  {
    slug: "stopspy",
    name: "StopSpy - Ultimate Protection",
    url: SHOPIFY("stopspy"),
    developer: "Supernova",
    launched: "2023-05-12",
    pricing: "$9.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Content and spy-extension blocking with a feature it calls a Public Sales Data Manipulator.",
    claims: ["Disable right-click, copy, and developer tools", "Block spy extensions", "Public Sales Data Manipulator"],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "spy-extension-block"],
  },
  {
    slug: "r-blocker",
    name: "R Blocker",
    url: SHOPIFY("r-blocker"),
    developer: "Techspark",
    launched: "2021-09-14",
    pricing: "$1.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Right-click, copy, and image-save blocking with a stated PrintScreen prevention and geo/IP filtering.",
    claims: ["Disable right-click, copying, and image saving", "Prevent PrintScreen", "Geo and IP blocking"],
    mechanisms: ["right-click-block", "copy-paste-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "disable-toolbox-country-block",
    name: "Shopupup Disable Toolbox",
    url: SHOPIFY("disable-toolbox-country-block"),
    developer: "ShopUpUp",
    launched: "2024-07-12",
    pricing: "Free plan; paid $1.90/mo",
    primary: "bundle",
    featured: false,
    summary: "Access filtering by country, IP, VPN, and bot status, including user-agent based browser blocking, plus copy and devtools blocking.",
    claims: [
      "Disable Chinese browser access",
      "Country, IP, VPN, and bot blocking",
      "Disable copy and developer tools",
    ],
    mechanisms: ["copy-paste-block", "devtools-block", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "smart-content-protector",
    name: "Smart Content Protector",
    url: SHOPIFY("smart-content-protector"),
    developer: "sea-apps",
    launched: "2020-02-18",
    pricing: "$4.99/mo",
    primary: "blocker",
    featured: false,
    summary: "Right-click, copy, and developer-shortcut blocking with a customisable legal notice.",
    claims: ["Disable right-click, copy, and developer shortcuts", "Custom legal notice"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block"],
  },
  {
    slug: "ghostify",
    name: "Anti Spy - Blocker, Filter",
    url: SHOPIFY("ghostify"),
    developer: "Novera Digital Group",
    launched: "2026-05-11",
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Free spy-extension blocking against named tools with right-click and copy blocking.",
    claims: [
      "Block spy extensions such as PPSpy, AliHunter, Koala Inspector, and ShopHunter",
      "Disable right-click and copying",
      "Block web scraping",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "spy-extension-block"],
  },
  {
    slug: "veloshield",
    name: "VeloShield: Disable Image Copy",
    url: SHOPIFY("veloshield"),
    developer: "ADA",
    launched: "2026-05-27",
    pricing: "Free plan; paid $1.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Content blocking with best-seller sort hiding and a security score; the paid plan adds geo and IP filtering.",
    claims: [
      "Disable right-click, copy, and developer tools",
      "Hide best-selling sort",
      "Security score; Pro adds geo and IP blocking",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "spy-extension-block", "country-ip-block"],
  },
  {
    slug: "fire-protect",
    name: "Fire Protect",
    url: SHOPIFY("fire-protect"),
    developer: "Glow",
    launched: "2024-04-10",
    pricing: "$9.90 to $48.50/mo",
    primary: "bundle",
    featured: false,
    summary: "Content and spy-extension blocking with fake-purchase blocking and developer-mode blocking.",
    claims: [
      "Disable right-click, copy, and F12/Ctrl+U",
      "Fake purchase blocking and developer mode blocking",
      "Spy-extension blocking",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "spy-extension-block"],
  },
  {
    slug: "anti-spy",
    name: "Anti-Spy.io",
    url: SHOPIFY("anti-spy"),
    developer: "DevXpertise",
    launched: "2023-09-21",
    pricing: "$5/mo",
    primary: "bundle",
    featured: false,
    summary: "Spy-extension blocking against named tools with right-click, copy, and developer-tools blocking.",
    claims: [
      "Block spy tools such as Dropship.io, AliHunter, PPSpy, UUSpy, and Shopify Raise",
      "Disable right-click, copy, and developer tools",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "spy-extension-block"],
  },
  {
    slug: "shopsecure",
    name: "Shop Secure",
    url: SHOPIFY("shopsecure"),
    developer: "ShopiShore",
    launched: "2026-01-23",
    pricing: "$1.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Country blocking with per-country product and collection hiding, IP filtering, and content blocking.",
    claims: [
      "Country blocking with per-country product and collection hiding",
      "Disable right-click, copy, and screenshots",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "right-click-blocker",
    name: "Pioneer Right Click Blocker",
    url: SHOPIFY("right-click-blocker"),
    developer: "PK Pioneers",
    launched: "2023-03-13",
    rating: "5.0",
    reviews: 1,
    pricing: "$3 to $9.99/mo",
    primary: "blocker",
    featured: false,
    summary: "A blocker whose paid tiers list Screenshot Block, Print Block, F12 blocking, and an auto-blur effect on focus loss.",
    claims: ["Screenshot Block and Print Block on paid tiers", "Auto Blur on focus loss", "F12 blocking"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "screenshot-deter"],
  },
  {
    slug: "clicky-one-click-stickybar",
    name: "SafeShield: Protect Data",
    url: SHOPIFY("clicky-one-click-stickybar"),
    developer: "ShopBooster",
    launched: "2023-06-30",
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Free right-click, copy, image-save, and shortcut blocking with spy-extension blocking.",
    claims: ["Disable right-click, copy, image saving, and shortcuts", "Spy-extension blocking"],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "spy-extension-block"],
  },
  {
    slug: "siteshield-app-pro",
    name: "Block - Block IPs & Country",
    url: SHOPIFY("siteshield-app-pro"),
    developer: "Bootsgrid",
    launched: "2025-05-20",
    pricing: "$2/mo",
    primary: "bundle",
    featured: false,
    summary: "Country and IP blocking with right-click, copy, and print-screen blocking.",
    claims: ["Country and IP blocking", "Disable right-click, copy, and print screen"],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "anti-theft-protection",
    name: "Guarder: Anti Theft Protection",
    url: SHOPIFY("anti-theft-protection"),
    developer: "CodeRagon Infotech",
    launched: "2026-05-07",
    pricing: "Free",
    primary: "bundle",
    featured: false,
    summary: "Free content blocking including view-source and theme-code access claims, with country, IP, ASN, and city filtering and VPN detection.",
    claims: [
      "Disable right-click, copy, print, view source and theme code access",
      "Block by country, IP, ASN, and city, plus VPN detection",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block", "country-ip-block"],
  },
  {
    slug: "sa-070-ur-right-click-deny",
    name: "UR: Disable Right Click",
    url: SHOPIFY("sa-070-ur-right-click-deny"),
    developer: "UnReact Inc.",
    launched: "2025-04-17",
    pricing: "$5.99/mo",
    primary: "blocker",
    featured: false,
    summary: "A single-purpose app that disables right-click, with modest wording.",
    claims: ["Disable right-click on the storefront"],
    mechanisms: ["right-click-block"],
  },
  {
    slug: "magaza-korumasi-pro",
    name: "Store Protection Pro",
    url: SHOPIFY("magaza-korumasi-pro"),
    developer: "ERN DIGITAL",
    launched: "2026-01-13",
    pricing: "Free plan; paid $6.99/mo",
    primary: "bundle",
    featured: false,
    summary: "Free right-click and copy blocking; the premium plan adds geo, VPN, image, and developer-tools blocking with screenshot claims.",
    claims: [
      "Disable right-click and copy on the free plan",
      "Premium: geo, VPN, image, and developer-tools blocking, plus screenshot blocking",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "devtools-block", "screenshot-deter", "country-ip-block"],
  },
  {
    slug: "myshopguardian",
    name: "Myshopguardian",
    url: SHOPIFY("myshopguardian"),
    developer: "DTechies",
    launched: "2026-06-04",
    pricing: "Free",
    primary: "blocker",
    featured: false,
    summary: "Free right-click, clipboard, and selection blocking, disclosed as a client-side theme block, with user-agent based browser restrictions.",
    claims: [
      "Disable right-click, clipboard copy, and selection",
      "Restrict shopfront access from Chrome or Safari browsers",
      "A theme block that runs client-side",
    ],
    mechanisms: ["right-click-block", "copy-paste-block"],
  },
  {
    slug: "disable-right-click-2",
    name: "EN: Disable Click",
    url: SHOPIFY("disable-right-click-2"),
    developer: "ENCYPHERS LLC",
    launched: "2026-05-27",
    pricing: "Free",
    primary: "blocker",
    featured: false,
    summary: "Free right-click, copy, image-save, F12, print, and save blocking, with broad data-protection wording.",
    claims: [
      "Disable right-click, copy, image saving, F12, print and save",
      "Protect store data, SEO content, and customer data",
    ],
    mechanisms: ["right-click-block", "copy-paste-block", "keyboard-shortcut-block", "devtools-block"],
  },
];

export const COMPETITORS: Competitor[] = [...FEATURED, ...TABLE_ONLY];
export const FEATURED_COMPETITORS = FEATURED;
export const TOTAL_COMPARED = COMPETITORS.length; // 83 relevant apps (7 off-category apps excluded)

export function countByApproach(a: Approach): number {
  return COMPETITORS.filter((c) => c.primary === a).length;
}

/** Apps whose stated mechanisms require a storefront script. */
export function countScriptApps(): number {
  return COMPETITORS.filter((c) => (c.mechanisms ?? []).some((m) => SCRIPT_MECHS.includes(m))).length;
}

/** Popularity order for every list on the site: review count descending, ties by rating then name. */
export function byPopularity(a: Competitor, b: Competitor): number {
  const r = (b.reviews ?? 0) - (a.reviews ?? 0);
  if (r !== 0) return r;
  const g = parseFloat(b.rating ?? "0") - parseFloat(a.rating ?? "0");
  if (g !== 0) return g;
  return a.name.localeCompare(b.name);
}

/** All apps in popularity order. */
export const COMPETITORS_BY_POPULARITY: Competitor[] = [...COMPETITORS].sort(byPopularity);

/**
 * Plain-words one-liner for the hub list: what each app does, in the fewest
 * honest words. Derived from each listing's stated features (June-July 2026).
 */
export const BLURBS: Record<string, string> = {
  "disable-mouse-right-click": "Blocks right-click, copying and shortcuts in the browser",
  "disable-copy-paste-country": "Blocks copying and filters visitors by country, IP and VPN",
  "store-shield": "Blocks copying and screens orders, IPs and VPNs",
  "no-spy": "Blocks copying and spy extensions, filters visitors by IP and VPN",
  "shogard": "Blocks copying and filters IPs, countries and bots",
  "kedra-shield-website-security": "Blocks copying and filters countries, IPs, VPNs and bots",
  "free-watermarks": "Stamps visible watermarks on product images",
  "cozy-antitheft-for-images-and-more": "Blocks right-click, shortcuts, printing and the console",
  "storelock": "Detects impersonating sites and sends takedown requests",
  "viking-watermark": "Stamps visible watermarks on product images in bulk",
  "suprimg-anti-theft-watermark": "Stamps visible watermarks and blocks right-click",
  "oh-watermark": "Stamps visible watermarks, with a storefront overlay option",
  "photolock": "Blocks copying and shields images in the browser",
  "imagearmor": "Stamps visible watermarks on product images in bulk",
  "ip-moat": "Scans marketplaces for counterfeits and files removals",
  "spyblocker-block-competitors": "Blocks copying and filters IPs and bots with a storefront script",
  "disable-right-click": "Blocks Save As, text selection and copying",
  "sgtlab-bulk-watermark": "Stamps visible watermarks on product images, pay as you go",
  "addify-image-watermark": "Stamps visible watermarks, applied automatically to new images",
  "defendify": "Blocks right-click and shortcuts as a deterrent",
  "tilkie-image-protection": "Invisibly watermarks product images and proves image theft",
  "mintallkeep": "Attaches C2PA credentials and NFT records to content",
  "disable-right-click-3": "Blocks image saving, copying and print shortcuts",
  "copycat-alert-product-monitor": "Scans chosen domains for copied text and images",
  "auto-image-watermark-seo": "Stamps visible watermarks in bulk, with image SEO extras",
  "copyblock": "Blocks right-click and copying as a theme embed",
  "qf-content-guard": "Stamps visible watermarks and blocks copying",
  "easy-block-customer-ip-country": "Blocks copying and filters countries, IPs, VPNs and bots",
  "sales-shield": "Blocks copying and spy extensions, feeds trackers fake data",
  "x-shield-store-guard": "Filters countries, IPs and bots, and blocks copying",
  "antitheft-pro": "Blocks right-click, inspect element and copying",
  "protos": "Blocks copying and filters countries, IPs, VPN and Tor",
  "scala-anti-spy": "Blocks copying, with country filtering",
  "shop-shield": "Blocks right-click, image saving and copying",
  "country-blockeer": "Blocks countries and bots, with copy blocking",
  "shop-protector-1": "Blocks developer tools and copying, restricts countries",
  "shieldify": "Blocks copying and printing, filters countries and VPNs",
  "koi-disable-right-click": "Blocks copying and named spy extensions",
  "securecommerce-1": "Blocks copying, filters visitors and watches for clone sites",
  "bl-content-protection": "Blocks right-click, copying and image saving",
  "disable-right": "Blocks copying and spy extensions, with geo and IP filtering",
  "firewall-ip-and-country-restriction": "Blocks countries, states and cities, with copy blocking",
  "easy-block": "Filters visitors by country, IP, language and timezone",
  "mega-content-protector": "Blocks copying, printing and the console on desktop and mobile",
  "shop-guard-app": "Blocks copying and touch-hold, with country filtering",
  "prevent-content-theft": "Blocks right-click, selection and shortcuts, restricts countries",
  "content-protection": "Blocks copying and spy extensions, with geo filtering",
  "anty-spy": "Blocks spy extensions, right-click and copying",
  "nocopy-plagiarism-guard": "Blocks copying and shows a copyright message",
  "salesdish-content-protection": "Blocks right-click, selection, printing and shortcuts",
  "shop-protector": "Blocks right-click, copying and view-source shortcuts",
  "right-click-disable": "Blocks right-click, copying and shortcuts",
  "switchboard-development": "A toggle suite with an anti-copy shield among its switches",
  "watchdog": "Blocks copying and filters countries, IPs and bots",
  "photosentry": "Blocks image saving and tracks blocked attempts",
  "clipboard-manager": "Blocks copying and appends an attribution link to copied text",
  "right-click-defender": "Blocks right-click, view-source and copying",
  "speed-defender": "Blocks copying and hides source code and best-seller sorting",
  "smart-security": "Blocks right-click and keyboard shortcuts",
  "shopprotect": "Blocks copying and hides the theme name",
  "dev-content-protector": "Blocks copying and printing, with spy and IP filtering",
  "store-fence": "Blocks states, cities and IPs, with copy blocking",
  "prevent-content-copying": "Blocks right-click, copying and developer tools",
  "aegis": "Blocks copying, with best-seller protection and country filtering",
  "dropship-protect": "Blocks named spy extensions, with geo and IP filtering",
  "threads": "Filters countries, proxies and bots",
  "stopspy": "Blocks copying and spy extensions, alters public sales data",
  "r-blocker": "Blocks copying and image saving, with geo and IP filtering",
  "disable-toolbox-country-block": "Filters countries, IPs, VPNs and selected browsers",
  "smart-content-protector": "Blocks copying, with a custom legal notice",
  "ghostify": "Blocks named spy extensions and copying",
  "veloshield": "Blocks copying and hides best-seller sorting",
  "fire-protect": "Blocks copying, spy extensions and fake purchases",
  "anti-spy": "Blocks named spy tools and copying",
  "shopsecure": "Blocks countries, with per-country product hiding and copy blocking",
  "right-click-blocker": "Blocks right-click, with print blocking and auto-blur on paid tiers",
  "clicky-one-click-stickybar": "Blocks copying, image saving and spy extensions",
  "siteshield-app-pro": "Blocks countries and IPs, with copy blocking",
  "anti-theft-protection": "Blocks copying and filters countries, IPs and cities",
  "sa-070-ur-right-click-deny": "Disables right-click on the storefront",
  "magaza-korumasi-pro": "Blocks right-click and copying, with geo and VPN filtering on paid plans",
  "myshopguardian": "Blocks right-click and copying as a client-side theme block",
  "disable-right-click-2": "Blocks right-click, copying, printing and image saving",
};
